---
 - name: access test
   hosts: all
   become: yes

   tasks:
    - name: execute command hostname 
      ansible.builtin.shell: hostname -A
      register: result
    - name: show output
      ansible.builtin.debug:
        var: result

    - name: get log 
      ansible.builtin.shell:  tail -f -n 20 /var/log/messages
      register: log_result
    - name: shlw log
      ansible.builtin.debug:
        var: log_result
