---
 - name: access test
   hosts: all
   become: yes

   tasks:
    - name: execute command hostname 
      ansible.builtin.command: hostname -A
      register: command_output
    - name: show output
      ansible.builtin.debug:
        var: commnad_output
        verbosity: 2