---
 - name: access test
   hosts: all
   become: yes

   tasks:
    - name: execute command hostname 
      ansible.builtin.shell: hostname -A
      register: result
    - name: show output
      ansible.builtin.debug:
        var: result
        verbosity: 2