---
 - name: access test
   hosts: all
   become: yes

   tasks:
    - name: execute command hostname 
      ansible.builtin.command: hostname -A
      register: command_output
    - name: show output
      debug:
      msg: {{ command_output.stdout }}
