---
 - name: service_status
   hosts: all
   become: yes
   vars:
     service_name: httpd
     service_state: started 

   tasks:
     - name: service install
       ansible.builtin.package:
         name: 
           - httpd
         state: latest
    
     - name: Start service httpd, if not started
       service:
         name: '{{ service_name }}'
         state: '{{ service_state }}'