---
 - name: create_rhel_vm
   hosts: localhost
   become: yes
   vars:
     vm_name: 'rhel-demo'
     aws_region: 'us-east-2'
     aws_keypair_name: 'aap-key'
     aws_vpc_subnet_name: 'AAP-subnet-private1-us-east-2a'
     aws_security_group_name: 'aap-sg1'
#     vm_blueprint: 'rhel9'
#     aws_instance_ami_rhel9: 'ami-02b8534ff4b424939'
#     aws_instance_ami_rhel8: 'ami-068ee501b16366120'
#     aws_instance_ami_win2019: 'ami-0a1a6272c3e138311'
#     aws_instance_ami_amazon2023: 'ami-0ccabb5f82d4c9af5'
#     aws_instance_ami: '{{ aws_instance_ami_rhel9 }}'
     aws_instance_size: 't3.micro'
   vars_files:
     - ../vm_blueprint/{{ vm_blueprint }}.yml  
#   debug:
#     msg: '{{ aws_instance_ami }}'

   tasks:
     - name: start an instance with a private IP address
       amazon.aws.ec2_instance:
         name: '{{ vm_name }}'
         key_name: '{{ aws_keypair_name }}'
         vpc_subnet_id: '{{ aws_subnet_id }}'
         instance_type: '{{ aws_instance_size }}'
         security_group: '{{ aws_security_group_name }}'
         region: '{{ aws_region }}'
         network:
           assign_public_ip: false
         image_id: '{{ aws_instance_ami }}'
         tags:
           Environment: DEMO
           Name: '{{ vm_name }}'

     - name: Wait for VM Creation
       ansible.builtin.pause:
         minutes: 1

