---
 - name: create_rhel_vm
   hosts: localhost
   become: yes
   vars:
     vm_name: 'rhel-demo'
     aws_region: 'us-east-2'
     aws_keypair_name: 'EDA-KEY'
     aws_vpc_subnet_name: 'AAP-subnet-public1-us-east-2a'
     aws_security_group_name: 'RedHat-SG'
     vm_blueprint: 'rhel8'
     
   vars_files:
     - "vm_blueprints/{{ vm_blueprint }}.yml"

   tasks:
    - name: vars check
      ansible.builtin.debug:
        msg: aws_image_filter

    - name: Find ami
      amazon.aws.ec2_ami_info:
        region: "{{ aws_region }}"
        owners: "{{ aws_image_owners | default(omit) }}"
        filters:
          name: "{{ aws_image_filter }}"
          architecture: "{{ aws_image_architecture | default(omit) }}"
      register: vm_amis

    - name: Save ami
      ansible.builtin.set_fact:
        aws_instance_ami: >
          {{ (vm_amis.images | selectattr('name', 'defined') | sort(attribute='creation_date'))[-1].image_id }}

    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: '{{ vm_name }}'
        key_name: '{{ aws_keypair_name }}'
        vpc_subnet_id: '{{ aws_vpc_subnet_name }}'
        instance_type: '{{ aws_instance_size }}'
        security_group: '{{ aws_security_group_name }}'
        network:
        assign_public_ip: true
        image_id: '{{ aws_instance_ami }}'
        tags:
          Environment: DEMO
          Name: '{{ vm_name }}'
