---
 - name: create_rhel_vm
   hosts: localhost
   become: yes
   vars:
     vm_name: 'rhel-demo'
     aws_region: 'us-east-2'
     aws_keypair_name: 'EDA-KEY'
     aws_vpc_subnet_name: 'AAP-subnet-public1-us-east-2a'
     aws_security_group_name: 'RedHat-SG'
     vm_blueprint: 'rhel8'
     aws_instance_ami: 'ami-0091af26fbb64f3e1'
     
   vars_files:
     - 'vm_blueprints/{{ vm_blueprint }}.yml'

   tasks:
    - name: Get subnet info
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ aws_vpc_subnet_name }}"
      register: aws_subnet
      when: aws_subnet_id is not defined

    - name: Save subnet id
      ansible.builtin.set_fact:
        aws_subnet_id: "{{ aws_subnet.subnets | map(attribute='id') | list | last }}"
      when: aws_subnet_id is not defined

    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: '{{ vm_name }}'
        key_name: '{{ aws_keypair_name }}'
        vpc_subnet_id: '{{ aws_subnet_id }}'
        instance_type: '{{ aws_instance_size }}'
        security_group: '{{ aws_security_group_name }}'
        region: '{{ aws_region }}'
        network:
          assign_public_ip: true
        image_id: '{{ aws_instance_ami }}'
        tags:
          Environment: DEMO
          Name: '{{ vm_name }}'

    - name: Wait for VM Creation
      ansible.builtin.pause:
        minutes: 1

