---
 - name: get_log
   hosts: '{{ HOST }}'
   become: yes
   vars:
     logfile: /var/log/messages
     lines: 20

   tasks:
    - name: get log 
      ansible.builtin.shell:  tail -n {{ lines }} {{ logfile }}
      register: log_result

    - name: shlw log
      ansible.builtin.debug:
        var: log_result.stdout_lines