---
- hosts: "{{ vm_name }}"
  become: yes
  vars:
    package: httpd

  tasks:
    - name: Package Install for RHEL8/9
      ansible.builtin.dnf:
        name: '{{ package }}'
        state: latest
      when: ansible_facts['distribution_major_version'] == '8'
        or ansible_facts['distribution_major_version'] == '9'

    - name: Package Install for RHEL7
      ansible.builtin.yum:
        name: '{{ package }}'
        state: latest
      when: ansible_facts['distribution_major_version'] == '7'
   
    - name: Start Service
      ansible.builtin.service:
        name: '{{ package }}'
        state: started
        enabled: yes

