---
 - name: register-rhel
   hosts: {{ vm_host }}
   become: yes

   tasks:
    - name: register rehel
      redhat_subscription:
        state: present
        username: {{ username }}
        password: {{ password }}
        auto_attach: true
