---
- hosts: "{{ HOSTS }}"
  become: yes
  vars:
    package: "{{ PACKAGE }}"

  tasks:
    - name: 
      ansible.builtin.dnf:
        name: '{{ package }}'
        state: latest
      when: ansible_facts['distribution_major_version'] >= 8
    - name:
      ansible.builtin.yum:
        name: '{{ package }}'
        state: latest
      when: ansible_facts['distribution_major_version'] == '7'

