---
 - name: select os test
   hosts: localhost
   vars:
    vm_blueprint: 'rhel9'
    aws_instance_ami_rhel9: 'ami-02b8534ff4b424939'
    aws_instance_ami_rhel8: 'ami-068ee501b16366120'
    aws_instance_ami_win2019: 'ami-0a1a6272c3e138311'
    aws_instance_ami_amazon2023: 'ami-0ccabb5f82d4c9af5'
    set_aws_instance_ami: aws_instance_ami_{{ vm_blueprint }}
    aws_instance_ami: {{ set_aws_instance_ami }}


   tasks:
    - name: set os
      debug:
        msg: 
         - '{{ set_aws_instance_ami }}'
         - '{{ aws_instance_ami }}'

    - name: rhel9
      vars: 
        aws_instance_ami: '{{ aws_instance_ami_rhel9 }}'
      when: vm_blueprint == 'rhel9'
      debug:
       msg: '{{ aws_instance_ami }}'

        
    - name: rhel8
      vars: 
        aws_instance_ami: '{{ aws_instance_ami_rhel8 }}'
      when: vm_blueprint == 'rhel8'
      debug:
       msg: '{{ aws_instance_ami }}'

    - name: win2019
      vars: 
        aws_instance_ami: '{{ aws_instance_ami_win2019 }}'
      when: vm_blueprint == 'win2019'
      debug:
       msg: '{{ aws_instance_ami }}'

    - name: amazon2023
      vars: 
        aws_instance_ami: '{{ aws_instance_ami_amazon2023 }}'
      when: vm_blueprint == 'amazon2023'
      debug:
       msg: '{{ aws_instance_ami }}'

    - name: create VM
      vars: 
       aws_instance_ami: 
      debug:
       msg: '{{ aws_instance_ami }}'

